#pragma once

// From glfw3.h
#define ELYS_MOUSE_BUTTON_1         0
#define ELYS_MOUSE_BUTTON_2         1
#define ELYS_MOUSE_BUTTON_3         2
#define ELYS_MOUSE_BUTTON_4         3
#define ELYS_MOUSE_BUTTON_5         4
#define ELYS_MOUSE_BUTTON_6         5
#define ELYS_MOUSE_BUTTON_7         6
#define ELYS_MOUSE_BUTTON_8         7
#define ELYS_MOUSE_BUTTON_LAST      ELYS_MOUSE_BUTTON_8
#define ELYS_MOUSE_BUTTON_LEFT      ELYS_MOUSE_BUTTON_1
#define ELYS_MOUSE_BUTTON_RIGHT     ELYS_MOUSE_BUTTON_2
#define ELYS_MOUSE_BUTTON_MIDDLE    ELYS_MOUSE_BUTTON_3